# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0buserservice\x1a\x1bgoogle/protobuf/empty.proto\"%\n\x12GetUserbyIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"A\n\x13GetUserbyIdResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"F\n\x13GetAllUsersResponse\x12/\n\x05users\x18\x01 \x03(\x0b\x32 .userservice.GetUserbyIdResponse2\xa8\x01\n\x0bUserService\x12P\n\x0bGetUserbyId\x12\x1f.userservice.GetUserbyIdRequest\x1a .userservice.GetUserbyIdResponse\x12G\n\x0bGetAllUsers\x12\x16.google.protobuf.Empty\x1a .userservice.GetAllUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERBYIDREQUEST']._serialized_start=64
  _globals['_GETUSERBYIDREQUEST']._serialized_end=101
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=103
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=168
  _globals['_GETALLUSERSRESPONSE']._serialized_start=170
  _globals['_GETALLUSERSRESPONSE']._serialized_end=240
  _globals['_USERSERVICE']._serialized_start=243
  _globals['_USERSERVICE']._serialized_end=411
# @@protoc_insertion_point(module_scope)
